export const REQUEST_ROOM_MESSAGES = 'REQUEST_ROOM_MESSAGES';
export const REQUEST_ROOM_INFO = 'REQUEST_ROOM_INFO';
export const REQUEST_ROOMS = 'REQUEST_ROOMS';
export const POST_NEW_MESSAGE = 'POST_NEW_MESSAGE';